


spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.driverClassName=oracle.jdbc.OracleDriver
spring.datasource.username=system
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mohanshingare2018@gmail.com
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

